name: groot
recipe: wordpress
config:
  webroot: wp

services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install

  node:
    type: node:6.11

    globals:
      webpack: "4.0.0"
      grunt-cli: "1.2.0"
      yarn: "1.5.1"

    build:
      - cd $LANDO_MOUNT && yarn install

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.bash'
    description: 'Install and configure WordPress for custom theme dev'

  yarn:
    service: node

  grunt:
    service: node

  webpack:
    service: node

proxy:
  appserver:
    - groot.lndo.site

  mailhog:
    - mail.groot.lndo.site

events:
  post-install:
    # ensure WordPress is installed and configured
    - wp --path="$LANDO_MOUNT/wp" plugin uninstall hello akismet
    - wp --path="$LANDO_MOUNT/wp" plugin activate timber-library conifer
    - wp --path="$LANDO_MOUNT/wp" theme activate groot
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyfifteen twentysixteen twentyseventeen
